storage: /verdaccio/storage

listen:
  - 0.0.0.0:4873

auth:
  gitlab:
    url: http://gitlab
    authCache:
      enabled: true
      ttl: 300

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
    gitlab: true

  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs
    gitlab: true

logs:
  - {type: stdout, format: pretty, level: info }
  #- {type: file, path: verdaccio.log, level: info}
