// flow-typed signature: 391843f12084213473573dac75d13a5a
// flow-typed version: <<STUB>>/@commitlint/travis-cli_v7.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/travis-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/travis-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@commitlint/travis-cli/lib/cli' {
  declare module.exports: any;
}

declare module '@commitlint/travis-cli/lib/cli.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@commitlint/travis-cli/lib/cli.js' {
  declare module.exports: $Exports<'@commitlint/travis-cli/lib/cli'>;
}
declare module '@commitlint/travis-cli/lib/cli.test.js' {
  declare module.exports: $Exports<'@commitlint/travis-cli/lib/cli.test'>;
}
