// flow-typed signature: 47505ab7b4937903e60509d90998e68c
// flow-typed version: <<STUB>>/eclint_v^2.5.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eclint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eclint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eclint/bin/eclint' {
  declare module.exports: any;
}

declare module 'eclint/dist/cli' {
  declare module.exports: any;
}

declare module 'eclint/dist/doc' {
  declare module.exports: any;
}

declare module 'eclint/dist/eclint' {
  declare module.exports: any;
}

declare module 'eclint/dist/editor-config-error' {
  declare module.exports: any;
}

declare module 'eclint/dist/i18n' {
  declare module.exports: any;
}

declare module 'eclint/dist/rules/charset' {
  declare module.exports: any;
}

declare module 'eclint/dist/rules/end_of_line' {
  declare module.exports: any;
}

declare module 'eclint/dist/rules/indent_size' {
  declare module.exports: any;
}

declare module 'eclint/dist/rules/indent_style' {
  declare module.exports: any;
}

declare module 'eclint/dist/rules/insert_final_newline' {
  declare module.exports: any;
}

declare module 'eclint/dist/rules/max_line_length' {
  declare module.exports: any;
}

declare module 'eclint/dist/rules/trim_trailing_whitespace' {
  declare module.exports: any;
}

declare module 'eclint/dist/test-common' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eclint/bin/eclint.js' {
  declare module.exports: $Exports<'eclint/bin/eclint'>;
}
declare module 'eclint/dist/cli.js' {
  declare module.exports: $Exports<'eclint/dist/cli'>;
}
declare module 'eclint/dist/doc.js' {
  declare module.exports: $Exports<'eclint/dist/doc'>;
}
declare module 'eclint/dist/eclint.js' {
  declare module.exports: $Exports<'eclint/dist/eclint'>;
}
declare module 'eclint/dist/editor-config-error.js' {
  declare module.exports: $Exports<'eclint/dist/editor-config-error'>;
}
declare module 'eclint/dist/i18n.js' {
  declare module.exports: $Exports<'eclint/dist/i18n'>;
}
declare module 'eclint/dist/rules/charset.js' {
  declare module.exports: $Exports<'eclint/dist/rules/charset'>;
}
declare module 'eclint/dist/rules/end_of_line.js' {
  declare module.exports: $Exports<'eclint/dist/rules/end_of_line'>;
}
declare module 'eclint/dist/rules/indent_size.js' {
  declare module.exports: $Exports<'eclint/dist/rules/indent_size'>;
}
declare module 'eclint/dist/rules/indent_style.js' {
  declare module.exports: $Exports<'eclint/dist/rules/indent_style'>;
}
declare module 'eclint/dist/rules/insert_final_newline.js' {
  declare module.exports: $Exports<'eclint/dist/rules/insert_final_newline'>;
}
declare module 'eclint/dist/rules/max_line_length.js' {
  declare module.exports: $Exports<'eclint/dist/rules/max_line_length'>;
}
declare module 'eclint/dist/rules/trim_trailing_whitespace.js' {
  declare module.exports: $Exports<'eclint/dist/rules/trim_trailing_whitespace'>;
}
declare module 'eclint/dist/test-common.js' {
  declare module.exports: $Exports<'eclint/dist/test-common'>;
}
