// flow-typed signature: bf5dd9c7917034dfc0b0d3dd0caaa569
// flow-typed version: <<STUB>>/gitlab_v3.5.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gitlab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gitlab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gitlab/dist/es5/index' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/infrastructure/BaseService' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/infrastructure/Bundler' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/infrastructure/index' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/infrastructure/RequestHelper' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/infrastructure/XMLHttpRequester' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ApplicationSettings' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Branches' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/BroadcastMessages' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/CommitDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Commits' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/DeployKeys' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Deployments' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Environments' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/EpicDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/EpicIssues' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/EpicNotes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Epics' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Events' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/FeatureFlags' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/GeoNodes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/GitignoreTemplates' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/GitLabCIYMLTemplates' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/GroupAccessRequests' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/GroupBadges' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/GroupCustomAttributes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/GroupIssueBoards' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/GroupMembers' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/GroupMilestones' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/GroupProjects' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Groups' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/GroupVariables' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/index' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/IssueAwardEmojis' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/IssueDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/IssueNotes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Issues' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Jobs' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Keys' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Labels' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Licence' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/LicenceTemplates' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Lint' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/MergeRequestAwardEmojis' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/MergeRequestDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/MergeRequestNotes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/MergeRequests' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Namespaces' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/NotificationSettings' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/PagesDomains' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Pipelines' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/PipelineSchedules' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/PipelineScheduleVariables' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectAccessRequests' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectBadges' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectCustomAttributes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectHooks' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectImportExport' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectIssueBoards' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectMembers' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectMilestones' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Projects' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectSnippetAwardEmojis' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectSnippetDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectSnippetNotes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectSnippets' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProjectVariables' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/ProtectedBranches' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Repositories' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/RepositoryFiles' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Runners' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Search' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Services' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/SidekiqMetrics' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/SystemHooks' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Tags' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Todos' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Triggers' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/UserCustomAttributes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/UserEmails' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/UserGPGKeys' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/UserImpersonationTokens' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/UserKeys' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Users' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Version' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/services/Wikis' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/templates/index' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/templates/ResourceAccessRequests' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/templates/ResourceAwardEmojis' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/templates/ResourceBadges' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/templates/ResourceCustomAttributes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/templates/ResourceDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/templates/ResourceIssueBoards' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/templates/ResourceMembers' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/templates/ResourceMilestones' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/templates/ResourceNotes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/templates/ResourceTemplates' {
  declare module.exports: any;
}

declare module 'gitlab/dist/es5/templates/ResourceVariables' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/index' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/infrastructure/BaseService' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/infrastructure/Bundler' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/infrastructure/index' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/infrastructure/RequestHelper' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/infrastructure/XMLHttpRequester' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ApplicationSettings' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Branches' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/BroadcastMessages' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/CommitDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Commits' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/DeployKeys' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Deployments' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Environments' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/EpicDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/EpicIssues' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/EpicNotes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Epics' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Events' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/FeatureFlags' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/GeoNodes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/GitignoreTemplates' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/GitLabCIYMLTemplates' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/GroupAccessRequests' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/GroupBadges' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/GroupCustomAttributes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/GroupIssueBoards' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/GroupMembers' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/GroupMilestones' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/GroupProjects' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Groups' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/GroupVariables' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/index' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/IssueAwardEmojis' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/IssueDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/IssueNotes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Issues' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Jobs' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Keys' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Labels' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Licence' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/LicenceTemplates' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Lint' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/MergeRequestAwardEmojis' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/MergeRequestDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/MergeRequestNotes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/MergeRequests' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Namespaces' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/NotificationSettings' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/PagesDomains' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Pipelines' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/PipelineSchedules' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/PipelineScheduleVariables' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectAccessRequests' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectBadges' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectCustomAttributes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectHooks' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectImportExport' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectIssueBoards' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectMembers' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectMilestones' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Projects' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectSnippetAwardEmojis' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectSnippetDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectSnippetNotes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectSnippets' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProjectVariables' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/ProtectedBranches' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Repositories' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/RepositoryFiles' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Runners' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Search' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Services' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/SidekiqMetrics' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/SystemHooks' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Tags' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Todos' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Triggers' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/UserCustomAttributes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/UserEmails' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/UserGPGKeys' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/UserImpersonationTokens' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/UserKeys' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Users' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Version' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/services/Wikis' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/templates/index' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/templates/ResourceAccessRequests' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/templates/ResourceAwardEmojis' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/templates/ResourceBadges' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/templates/ResourceCustomAttributes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/templates/ResourceDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/templates/ResourceIssueBoards' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/templates/ResourceMembers' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/templates/ResourceMilestones' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/templates/ResourceNotes' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/templates/ResourceTemplates' {
  declare module.exports: any;
}

declare module 'gitlab/dist/latest/templates/ResourceVariables' {
  declare module.exports: any;
}

declare module 'gitlab/jest.config' {
  declare module.exports: any;
}

declare module 'gitlab/src/index' {
  declare module.exports: any;
}

declare module 'gitlab/src/infrastructure/BaseService' {
  declare module.exports: any;
}

declare module 'gitlab/src/infrastructure/Bundler' {
  declare module.exports: any;
}

declare module 'gitlab/src/infrastructure/index' {
  declare module.exports: any;
}

declare module 'gitlab/src/infrastructure/RequestHelper' {
  declare module.exports: any;
}

declare module 'gitlab/src/infrastructure/XMLHttpRequester' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ApplicationSettings' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Branches' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/BroadcastMessages' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/CommitDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Commits' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/DeployKeys' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Deployments' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Environments' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/EpicDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/EpicIssues' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/EpicNotes' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Epics' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Events' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/FeatureFlags' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/GeoNodes' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/GitignoreTemplates' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/GitLabCIYMLTemplates' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/GroupAccessRequests' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/GroupBadges' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/GroupCustomAttributes' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/GroupIssueBoards' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/GroupMembers' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/GroupMilestones' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/GroupProjects' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Groups' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/GroupVariables' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/index' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/IssueAwardEmojis' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/IssueDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/IssueNotes' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Issues' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Jobs' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Keys' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Labels' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Licence' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/LicenceTemplates' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Lint' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/MergeRequestAwardEmojis' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/MergeRequestDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/MergeRequestNotes' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/MergeRequests' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Namespaces' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/NotificationSettings' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/PagesDomains' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Pipelines' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/PipelineSchedules' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/PipelineScheduleVariables' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectAccessRequests' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectBadges' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectCustomAttributes' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectHooks' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectImportExport' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectIssueBoards' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectMembers' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectMilestones' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Projects' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectSnippetAwardEmojis' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectSnippetDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectSnippetNotes' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectSnippets' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProjectVariables' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/ProtectedBranches' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Repositories' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/RepositoryFiles' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Runners' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Search' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Services' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/SidekiqMetrics' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/SystemHooks' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Tags' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Todos' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Triggers' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/UserCustomAttributes' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/UserEmails' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/UserGPGKeys' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/UserImpersonationTokens' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/UserKeys' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Users' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Version' {
  declare module.exports: any;
}

declare module 'gitlab/src/services/Wikis' {
  declare module.exports: any;
}

declare module 'gitlab/src/templates/index' {
  declare module.exports: any;
}

declare module 'gitlab/src/templates/ResourceAccessRequests' {
  declare module.exports: any;
}

declare module 'gitlab/src/templates/ResourceAwardEmojis' {
  declare module.exports: any;
}

declare module 'gitlab/src/templates/ResourceBadges' {
  declare module.exports: any;
}

declare module 'gitlab/src/templates/ResourceCustomAttributes' {
  declare module.exports: any;
}

declare module 'gitlab/src/templates/ResourceDiscussions' {
  declare module.exports: any;
}

declare module 'gitlab/src/templates/ResourceIssueBoards' {
  declare module.exports: any;
}

declare module 'gitlab/src/templates/ResourceMembers' {
  declare module.exports: any;
}

declare module 'gitlab/src/templates/ResourceMilestones' {
  declare module.exports: any;
}

declare module 'gitlab/src/templates/ResourceNotes' {
  declare module.exports: any;
}

declare module 'gitlab/src/templates/ResourceTemplates' {
  declare module.exports: any;
}

declare module 'gitlab/src/templates/ResourceVariables' {
  declare module.exports: any;
}

declare module 'gitlab/test/tests/bundles/GroupsBundle' {
  declare module.exports: any;
}

declare module 'gitlab/test/tests/bundles/ProjectsBundle' {
  declare module.exports: any;
}

declare module 'gitlab/test/tests/bundles/UsersBundle' {
  declare module.exports: any;
}

declare module 'gitlab/test/tests/infrastructure/BaseService' {
  declare module.exports: any;
}

declare module 'gitlab/test/tests/infrastructure/Bundle' {
  declare module.exports: any;
}

declare module 'gitlab/test/tests/infrastructure/RequestHelper' {
  declare module.exports: any;
}

declare module 'gitlab/test/tests/services/ApplicationSettings' {
  declare module.exports: any;
}

declare module 'gitlab/test/tests/services/Projects' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gitlab/dist/es5/index.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/index'>;
}
declare module 'gitlab/dist/es5/infrastructure/BaseService.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/infrastructure/BaseService'>;
}
declare module 'gitlab/dist/es5/infrastructure/Bundler.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/infrastructure/Bundler'>;
}
declare module 'gitlab/dist/es5/infrastructure/index.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/infrastructure/index'>;
}
declare module 'gitlab/dist/es5/infrastructure/RequestHelper.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/infrastructure/RequestHelper'>;
}
declare module 'gitlab/dist/es5/infrastructure/XMLHttpRequester.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/infrastructure/XMLHttpRequester'>;
}
declare module 'gitlab/dist/es5/services/ApplicationSettings.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ApplicationSettings'>;
}
declare module 'gitlab/dist/es5/services/Branches.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Branches'>;
}
declare module 'gitlab/dist/es5/services/BroadcastMessages.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/BroadcastMessages'>;
}
declare module 'gitlab/dist/es5/services/CommitDiscussions.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/CommitDiscussions'>;
}
declare module 'gitlab/dist/es5/services/Commits.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Commits'>;
}
declare module 'gitlab/dist/es5/services/DeployKeys.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/DeployKeys'>;
}
declare module 'gitlab/dist/es5/services/Deployments.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Deployments'>;
}
declare module 'gitlab/dist/es5/services/Environments.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Environments'>;
}
declare module 'gitlab/dist/es5/services/EpicDiscussions.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/EpicDiscussions'>;
}
declare module 'gitlab/dist/es5/services/EpicIssues.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/EpicIssues'>;
}
declare module 'gitlab/dist/es5/services/EpicNotes.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/EpicNotes'>;
}
declare module 'gitlab/dist/es5/services/Epics.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Epics'>;
}
declare module 'gitlab/dist/es5/services/Events.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Events'>;
}
declare module 'gitlab/dist/es5/services/FeatureFlags.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/FeatureFlags'>;
}
declare module 'gitlab/dist/es5/services/GeoNodes.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/GeoNodes'>;
}
declare module 'gitlab/dist/es5/services/GitignoreTemplates.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/GitignoreTemplates'>;
}
declare module 'gitlab/dist/es5/services/GitLabCIYMLTemplates.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/GitLabCIYMLTemplates'>;
}
declare module 'gitlab/dist/es5/services/GroupAccessRequests.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/GroupAccessRequests'>;
}
declare module 'gitlab/dist/es5/services/GroupBadges.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/GroupBadges'>;
}
declare module 'gitlab/dist/es5/services/GroupCustomAttributes.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/GroupCustomAttributes'>;
}
declare module 'gitlab/dist/es5/services/GroupIssueBoards.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/GroupIssueBoards'>;
}
declare module 'gitlab/dist/es5/services/GroupMembers.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/GroupMembers'>;
}
declare module 'gitlab/dist/es5/services/GroupMilestones.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/GroupMilestones'>;
}
declare module 'gitlab/dist/es5/services/GroupProjects.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/GroupProjects'>;
}
declare module 'gitlab/dist/es5/services/Groups.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Groups'>;
}
declare module 'gitlab/dist/es5/services/GroupVariables.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/GroupVariables'>;
}
declare module 'gitlab/dist/es5/services/index.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/index'>;
}
declare module 'gitlab/dist/es5/services/IssueAwardEmojis.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/IssueAwardEmojis'>;
}
declare module 'gitlab/dist/es5/services/IssueDiscussions.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/IssueDiscussions'>;
}
declare module 'gitlab/dist/es5/services/IssueNotes.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/IssueNotes'>;
}
declare module 'gitlab/dist/es5/services/Issues.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Issues'>;
}
declare module 'gitlab/dist/es5/services/Jobs.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Jobs'>;
}
declare module 'gitlab/dist/es5/services/Keys.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Keys'>;
}
declare module 'gitlab/dist/es5/services/Labels.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Labels'>;
}
declare module 'gitlab/dist/es5/services/Licence.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Licence'>;
}
declare module 'gitlab/dist/es5/services/LicenceTemplates.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/LicenceTemplates'>;
}
declare module 'gitlab/dist/es5/services/Lint.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Lint'>;
}
declare module 'gitlab/dist/es5/services/MergeRequestAwardEmojis.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/MergeRequestAwardEmojis'>;
}
declare module 'gitlab/dist/es5/services/MergeRequestDiscussions.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/MergeRequestDiscussions'>;
}
declare module 'gitlab/dist/es5/services/MergeRequestNotes.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/MergeRequestNotes'>;
}
declare module 'gitlab/dist/es5/services/MergeRequests.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/MergeRequests'>;
}
declare module 'gitlab/dist/es5/services/Namespaces.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Namespaces'>;
}
declare module 'gitlab/dist/es5/services/NotificationSettings.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/NotificationSettings'>;
}
declare module 'gitlab/dist/es5/services/PagesDomains.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/PagesDomains'>;
}
declare module 'gitlab/dist/es5/services/Pipelines.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Pipelines'>;
}
declare module 'gitlab/dist/es5/services/PipelineSchedules.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/PipelineSchedules'>;
}
declare module 'gitlab/dist/es5/services/PipelineScheduleVariables.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/PipelineScheduleVariables'>;
}
declare module 'gitlab/dist/es5/services/ProjectAccessRequests.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectAccessRequests'>;
}
declare module 'gitlab/dist/es5/services/ProjectBadges.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectBadges'>;
}
declare module 'gitlab/dist/es5/services/ProjectCustomAttributes.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectCustomAttributes'>;
}
declare module 'gitlab/dist/es5/services/ProjectHooks.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectHooks'>;
}
declare module 'gitlab/dist/es5/services/ProjectImportExport.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectImportExport'>;
}
declare module 'gitlab/dist/es5/services/ProjectIssueBoards.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectIssueBoards'>;
}
declare module 'gitlab/dist/es5/services/ProjectMembers.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectMembers'>;
}
declare module 'gitlab/dist/es5/services/ProjectMilestones.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectMilestones'>;
}
declare module 'gitlab/dist/es5/services/Projects.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Projects'>;
}
declare module 'gitlab/dist/es5/services/ProjectSnippetAwardEmojis.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectSnippetAwardEmojis'>;
}
declare module 'gitlab/dist/es5/services/ProjectSnippetDiscussions.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectSnippetDiscussions'>;
}
declare module 'gitlab/dist/es5/services/ProjectSnippetNotes.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectSnippetNotes'>;
}
declare module 'gitlab/dist/es5/services/ProjectSnippets.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectSnippets'>;
}
declare module 'gitlab/dist/es5/services/ProjectVariables.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProjectVariables'>;
}
declare module 'gitlab/dist/es5/services/ProtectedBranches.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/ProtectedBranches'>;
}
declare module 'gitlab/dist/es5/services/Repositories.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Repositories'>;
}
declare module 'gitlab/dist/es5/services/RepositoryFiles.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/RepositoryFiles'>;
}
declare module 'gitlab/dist/es5/services/Runners.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Runners'>;
}
declare module 'gitlab/dist/es5/services/Search.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Search'>;
}
declare module 'gitlab/dist/es5/services/Services.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Services'>;
}
declare module 'gitlab/dist/es5/services/SidekiqMetrics.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/SidekiqMetrics'>;
}
declare module 'gitlab/dist/es5/services/SystemHooks.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/SystemHooks'>;
}
declare module 'gitlab/dist/es5/services/Tags.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Tags'>;
}
declare module 'gitlab/dist/es5/services/Todos.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Todos'>;
}
declare module 'gitlab/dist/es5/services/Triggers.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Triggers'>;
}
declare module 'gitlab/dist/es5/services/UserCustomAttributes.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/UserCustomAttributes'>;
}
declare module 'gitlab/dist/es5/services/UserEmails.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/UserEmails'>;
}
declare module 'gitlab/dist/es5/services/UserGPGKeys.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/UserGPGKeys'>;
}
declare module 'gitlab/dist/es5/services/UserImpersonationTokens.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/UserImpersonationTokens'>;
}
declare module 'gitlab/dist/es5/services/UserKeys.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/UserKeys'>;
}
declare module 'gitlab/dist/es5/services/Users.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Users'>;
}
declare module 'gitlab/dist/es5/services/Version.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Version'>;
}
declare module 'gitlab/dist/es5/services/Wikis.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/services/Wikis'>;
}
declare module 'gitlab/dist/es5/templates/index.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/templates/index'>;
}
declare module 'gitlab/dist/es5/templates/ResourceAccessRequests.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/templates/ResourceAccessRequests'>;
}
declare module 'gitlab/dist/es5/templates/ResourceAwardEmojis.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/templates/ResourceAwardEmojis'>;
}
declare module 'gitlab/dist/es5/templates/ResourceBadges.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/templates/ResourceBadges'>;
}
declare module 'gitlab/dist/es5/templates/ResourceCustomAttributes.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/templates/ResourceCustomAttributes'>;
}
declare module 'gitlab/dist/es5/templates/ResourceDiscussions.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/templates/ResourceDiscussions'>;
}
declare module 'gitlab/dist/es5/templates/ResourceIssueBoards.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/templates/ResourceIssueBoards'>;
}
declare module 'gitlab/dist/es5/templates/ResourceMembers.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/templates/ResourceMembers'>;
}
declare module 'gitlab/dist/es5/templates/ResourceMilestones.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/templates/ResourceMilestones'>;
}
declare module 'gitlab/dist/es5/templates/ResourceNotes.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/templates/ResourceNotes'>;
}
declare module 'gitlab/dist/es5/templates/ResourceTemplates.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/templates/ResourceTemplates'>;
}
declare module 'gitlab/dist/es5/templates/ResourceVariables.js' {
  declare module.exports: $Exports<'gitlab/dist/es5/templates/ResourceVariables'>;
}
declare module 'gitlab/dist/latest/index.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/index'>;
}
declare module 'gitlab/dist/latest/infrastructure/BaseService.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/infrastructure/BaseService'>;
}
declare module 'gitlab/dist/latest/infrastructure/Bundler.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/infrastructure/Bundler'>;
}
declare module 'gitlab/dist/latest/infrastructure/index.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/infrastructure/index'>;
}
declare module 'gitlab/dist/latest/infrastructure/RequestHelper.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/infrastructure/RequestHelper'>;
}
declare module 'gitlab/dist/latest/infrastructure/XMLHttpRequester.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/infrastructure/XMLHttpRequester'>;
}
declare module 'gitlab/dist/latest/services/ApplicationSettings.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ApplicationSettings'>;
}
declare module 'gitlab/dist/latest/services/Branches.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Branches'>;
}
declare module 'gitlab/dist/latest/services/BroadcastMessages.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/BroadcastMessages'>;
}
declare module 'gitlab/dist/latest/services/CommitDiscussions.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/CommitDiscussions'>;
}
declare module 'gitlab/dist/latest/services/Commits.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Commits'>;
}
declare module 'gitlab/dist/latest/services/DeployKeys.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/DeployKeys'>;
}
declare module 'gitlab/dist/latest/services/Deployments.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Deployments'>;
}
declare module 'gitlab/dist/latest/services/Environments.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Environments'>;
}
declare module 'gitlab/dist/latest/services/EpicDiscussions.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/EpicDiscussions'>;
}
declare module 'gitlab/dist/latest/services/EpicIssues.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/EpicIssues'>;
}
declare module 'gitlab/dist/latest/services/EpicNotes.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/EpicNotes'>;
}
declare module 'gitlab/dist/latest/services/Epics.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Epics'>;
}
declare module 'gitlab/dist/latest/services/Events.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Events'>;
}
declare module 'gitlab/dist/latest/services/FeatureFlags.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/FeatureFlags'>;
}
declare module 'gitlab/dist/latest/services/GeoNodes.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/GeoNodes'>;
}
declare module 'gitlab/dist/latest/services/GitignoreTemplates.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/GitignoreTemplates'>;
}
declare module 'gitlab/dist/latest/services/GitLabCIYMLTemplates.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/GitLabCIYMLTemplates'>;
}
declare module 'gitlab/dist/latest/services/GroupAccessRequests.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/GroupAccessRequests'>;
}
declare module 'gitlab/dist/latest/services/GroupBadges.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/GroupBadges'>;
}
declare module 'gitlab/dist/latest/services/GroupCustomAttributes.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/GroupCustomAttributes'>;
}
declare module 'gitlab/dist/latest/services/GroupIssueBoards.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/GroupIssueBoards'>;
}
declare module 'gitlab/dist/latest/services/GroupMembers.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/GroupMembers'>;
}
declare module 'gitlab/dist/latest/services/GroupMilestones.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/GroupMilestones'>;
}
declare module 'gitlab/dist/latest/services/GroupProjects.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/GroupProjects'>;
}
declare module 'gitlab/dist/latest/services/Groups.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Groups'>;
}
declare module 'gitlab/dist/latest/services/GroupVariables.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/GroupVariables'>;
}
declare module 'gitlab/dist/latest/services/index.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/index'>;
}
declare module 'gitlab/dist/latest/services/IssueAwardEmojis.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/IssueAwardEmojis'>;
}
declare module 'gitlab/dist/latest/services/IssueDiscussions.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/IssueDiscussions'>;
}
declare module 'gitlab/dist/latest/services/IssueNotes.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/IssueNotes'>;
}
declare module 'gitlab/dist/latest/services/Issues.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Issues'>;
}
declare module 'gitlab/dist/latest/services/Jobs.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Jobs'>;
}
declare module 'gitlab/dist/latest/services/Keys.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Keys'>;
}
declare module 'gitlab/dist/latest/services/Labels.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Labels'>;
}
declare module 'gitlab/dist/latest/services/Licence.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Licence'>;
}
declare module 'gitlab/dist/latest/services/LicenceTemplates.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/LicenceTemplates'>;
}
declare module 'gitlab/dist/latest/services/Lint.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Lint'>;
}
declare module 'gitlab/dist/latest/services/MergeRequestAwardEmojis.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/MergeRequestAwardEmojis'>;
}
declare module 'gitlab/dist/latest/services/MergeRequestDiscussions.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/MergeRequestDiscussions'>;
}
declare module 'gitlab/dist/latest/services/MergeRequestNotes.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/MergeRequestNotes'>;
}
declare module 'gitlab/dist/latest/services/MergeRequests.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/MergeRequests'>;
}
declare module 'gitlab/dist/latest/services/Namespaces.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Namespaces'>;
}
declare module 'gitlab/dist/latest/services/NotificationSettings.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/NotificationSettings'>;
}
declare module 'gitlab/dist/latest/services/PagesDomains.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/PagesDomains'>;
}
declare module 'gitlab/dist/latest/services/Pipelines.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Pipelines'>;
}
declare module 'gitlab/dist/latest/services/PipelineSchedules.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/PipelineSchedules'>;
}
declare module 'gitlab/dist/latest/services/PipelineScheduleVariables.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/PipelineScheduleVariables'>;
}
declare module 'gitlab/dist/latest/services/ProjectAccessRequests.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectAccessRequests'>;
}
declare module 'gitlab/dist/latest/services/ProjectBadges.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectBadges'>;
}
declare module 'gitlab/dist/latest/services/ProjectCustomAttributes.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectCustomAttributes'>;
}
declare module 'gitlab/dist/latest/services/ProjectHooks.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectHooks'>;
}
declare module 'gitlab/dist/latest/services/ProjectImportExport.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectImportExport'>;
}
declare module 'gitlab/dist/latest/services/ProjectIssueBoards.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectIssueBoards'>;
}
declare module 'gitlab/dist/latest/services/ProjectMembers.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectMembers'>;
}
declare module 'gitlab/dist/latest/services/ProjectMilestones.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectMilestones'>;
}
declare module 'gitlab/dist/latest/services/Projects.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Projects'>;
}
declare module 'gitlab/dist/latest/services/ProjectSnippetAwardEmojis.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectSnippetAwardEmojis'>;
}
declare module 'gitlab/dist/latest/services/ProjectSnippetDiscussions.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectSnippetDiscussions'>;
}
declare module 'gitlab/dist/latest/services/ProjectSnippetNotes.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectSnippetNotes'>;
}
declare module 'gitlab/dist/latest/services/ProjectSnippets.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectSnippets'>;
}
declare module 'gitlab/dist/latest/services/ProjectVariables.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProjectVariables'>;
}
declare module 'gitlab/dist/latest/services/ProtectedBranches.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/ProtectedBranches'>;
}
declare module 'gitlab/dist/latest/services/Repositories.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Repositories'>;
}
declare module 'gitlab/dist/latest/services/RepositoryFiles.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/RepositoryFiles'>;
}
declare module 'gitlab/dist/latest/services/Runners.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Runners'>;
}
declare module 'gitlab/dist/latest/services/Search.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Search'>;
}
declare module 'gitlab/dist/latest/services/Services.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Services'>;
}
declare module 'gitlab/dist/latest/services/SidekiqMetrics.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/SidekiqMetrics'>;
}
declare module 'gitlab/dist/latest/services/SystemHooks.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/SystemHooks'>;
}
declare module 'gitlab/dist/latest/services/Tags.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Tags'>;
}
declare module 'gitlab/dist/latest/services/Todos.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Todos'>;
}
declare module 'gitlab/dist/latest/services/Triggers.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Triggers'>;
}
declare module 'gitlab/dist/latest/services/UserCustomAttributes.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/UserCustomAttributes'>;
}
declare module 'gitlab/dist/latest/services/UserEmails.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/UserEmails'>;
}
declare module 'gitlab/dist/latest/services/UserGPGKeys.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/UserGPGKeys'>;
}
declare module 'gitlab/dist/latest/services/UserImpersonationTokens.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/UserImpersonationTokens'>;
}
declare module 'gitlab/dist/latest/services/UserKeys.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/UserKeys'>;
}
declare module 'gitlab/dist/latest/services/Users.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Users'>;
}
declare module 'gitlab/dist/latest/services/Version.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Version'>;
}
declare module 'gitlab/dist/latest/services/Wikis.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/services/Wikis'>;
}
declare module 'gitlab/dist/latest/templates/index.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/templates/index'>;
}
declare module 'gitlab/dist/latest/templates/ResourceAccessRequests.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/templates/ResourceAccessRequests'>;
}
declare module 'gitlab/dist/latest/templates/ResourceAwardEmojis.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/templates/ResourceAwardEmojis'>;
}
declare module 'gitlab/dist/latest/templates/ResourceBadges.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/templates/ResourceBadges'>;
}
declare module 'gitlab/dist/latest/templates/ResourceCustomAttributes.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/templates/ResourceCustomAttributes'>;
}
declare module 'gitlab/dist/latest/templates/ResourceDiscussions.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/templates/ResourceDiscussions'>;
}
declare module 'gitlab/dist/latest/templates/ResourceIssueBoards.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/templates/ResourceIssueBoards'>;
}
declare module 'gitlab/dist/latest/templates/ResourceMembers.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/templates/ResourceMembers'>;
}
declare module 'gitlab/dist/latest/templates/ResourceMilestones.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/templates/ResourceMilestones'>;
}
declare module 'gitlab/dist/latest/templates/ResourceNotes.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/templates/ResourceNotes'>;
}
declare module 'gitlab/dist/latest/templates/ResourceTemplates.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/templates/ResourceTemplates'>;
}
declare module 'gitlab/dist/latest/templates/ResourceVariables.js' {
  declare module.exports: $Exports<'gitlab/dist/latest/templates/ResourceVariables'>;
}
declare module 'gitlab/jest.config.js' {
  declare module.exports: $Exports<'gitlab/jest.config'>;
}
declare module 'gitlab/src/index.js' {
  declare module.exports: $Exports<'gitlab/src/index'>;
}
declare module 'gitlab/src/infrastructure/BaseService.js' {
  declare module.exports: $Exports<'gitlab/src/infrastructure/BaseService'>;
}
declare module 'gitlab/src/infrastructure/Bundler.js' {
  declare module.exports: $Exports<'gitlab/src/infrastructure/Bundler'>;
}
declare module 'gitlab/src/infrastructure/index.js' {
  declare module.exports: $Exports<'gitlab/src/infrastructure/index'>;
}
declare module 'gitlab/src/infrastructure/RequestHelper.js' {
  declare module.exports: $Exports<'gitlab/src/infrastructure/RequestHelper'>;
}
declare module 'gitlab/src/infrastructure/XMLHttpRequester.js' {
  declare module.exports: $Exports<'gitlab/src/infrastructure/XMLHttpRequester'>;
}
declare module 'gitlab/src/services/ApplicationSettings.js' {
  declare module.exports: $Exports<'gitlab/src/services/ApplicationSettings'>;
}
declare module 'gitlab/src/services/Branches.js' {
  declare module.exports: $Exports<'gitlab/src/services/Branches'>;
}
declare module 'gitlab/src/services/BroadcastMessages.js' {
  declare module.exports: $Exports<'gitlab/src/services/BroadcastMessages'>;
}
declare module 'gitlab/src/services/CommitDiscussions.js' {
  declare module.exports: $Exports<'gitlab/src/services/CommitDiscussions'>;
}
declare module 'gitlab/src/services/Commits.js' {
  declare module.exports: $Exports<'gitlab/src/services/Commits'>;
}
declare module 'gitlab/src/services/DeployKeys.js' {
  declare module.exports: $Exports<'gitlab/src/services/DeployKeys'>;
}
declare module 'gitlab/src/services/Deployments.js' {
  declare module.exports: $Exports<'gitlab/src/services/Deployments'>;
}
declare module 'gitlab/src/services/Environments.js' {
  declare module.exports: $Exports<'gitlab/src/services/Environments'>;
}
declare module 'gitlab/src/services/EpicDiscussions.js' {
  declare module.exports: $Exports<'gitlab/src/services/EpicDiscussions'>;
}
declare module 'gitlab/src/services/EpicIssues.js' {
  declare module.exports: $Exports<'gitlab/src/services/EpicIssues'>;
}
declare module 'gitlab/src/services/EpicNotes.js' {
  declare module.exports: $Exports<'gitlab/src/services/EpicNotes'>;
}
declare module 'gitlab/src/services/Epics.js' {
  declare module.exports: $Exports<'gitlab/src/services/Epics'>;
}
declare module 'gitlab/src/services/Events.js' {
  declare module.exports: $Exports<'gitlab/src/services/Events'>;
}
declare module 'gitlab/src/services/FeatureFlags.js' {
  declare module.exports: $Exports<'gitlab/src/services/FeatureFlags'>;
}
declare module 'gitlab/src/services/GeoNodes.js' {
  declare module.exports: $Exports<'gitlab/src/services/GeoNodes'>;
}
declare module 'gitlab/src/services/GitignoreTemplates.js' {
  declare module.exports: $Exports<'gitlab/src/services/GitignoreTemplates'>;
}
declare module 'gitlab/src/services/GitLabCIYMLTemplates.js' {
  declare module.exports: $Exports<'gitlab/src/services/GitLabCIYMLTemplates'>;
}
declare module 'gitlab/src/services/GroupAccessRequests.js' {
  declare module.exports: $Exports<'gitlab/src/services/GroupAccessRequests'>;
}
declare module 'gitlab/src/services/GroupBadges.js' {
  declare module.exports: $Exports<'gitlab/src/services/GroupBadges'>;
}
declare module 'gitlab/src/services/GroupCustomAttributes.js' {
  declare module.exports: $Exports<'gitlab/src/services/GroupCustomAttributes'>;
}
declare module 'gitlab/src/services/GroupIssueBoards.js' {
  declare module.exports: $Exports<'gitlab/src/services/GroupIssueBoards'>;
}
declare module 'gitlab/src/services/GroupMembers.js' {
  declare module.exports: $Exports<'gitlab/src/services/GroupMembers'>;
}
declare module 'gitlab/src/services/GroupMilestones.js' {
  declare module.exports: $Exports<'gitlab/src/services/GroupMilestones'>;
}
declare module 'gitlab/src/services/GroupProjects.js' {
  declare module.exports: $Exports<'gitlab/src/services/GroupProjects'>;
}
declare module 'gitlab/src/services/Groups.js' {
  declare module.exports: $Exports<'gitlab/src/services/Groups'>;
}
declare module 'gitlab/src/services/GroupVariables.js' {
  declare module.exports: $Exports<'gitlab/src/services/GroupVariables'>;
}
declare module 'gitlab/src/services/index.js' {
  declare module.exports: $Exports<'gitlab/src/services/index'>;
}
declare module 'gitlab/src/services/IssueAwardEmojis.js' {
  declare module.exports: $Exports<'gitlab/src/services/IssueAwardEmojis'>;
}
declare module 'gitlab/src/services/IssueDiscussions.js' {
  declare module.exports: $Exports<'gitlab/src/services/IssueDiscussions'>;
}
declare module 'gitlab/src/services/IssueNotes.js' {
  declare module.exports: $Exports<'gitlab/src/services/IssueNotes'>;
}
declare module 'gitlab/src/services/Issues.js' {
  declare module.exports: $Exports<'gitlab/src/services/Issues'>;
}
declare module 'gitlab/src/services/Jobs.js' {
  declare module.exports: $Exports<'gitlab/src/services/Jobs'>;
}
declare module 'gitlab/src/services/Keys.js' {
  declare module.exports: $Exports<'gitlab/src/services/Keys'>;
}
declare module 'gitlab/src/services/Labels.js' {
  declare module.exports: $Exports<'gitlab/src/services/Labels'>;
}
declare module 'gitlab/src/services/Licence.js' {
  declare module.exports: $Exports<'gitlab/src/services/Licence'>;
}
declare module 'gitlab/src/services/LicenceTemplates.js' {
  declare module.exports: $Exports<'gitlab/src/services/LicenceTemplates'>;
}
declare module 'gitlab/src/services/Lint.js' {
  declare module.exports: $Exports<'gitlab/src/services/Lint'>;
}
declare module 'gitlab/src/services/MergeRequestAwardEmojis.js' {
  declare module.exports: $Exports<'gitlab/src/services/MergeRequestAwardEmojis'>;
}
declare module 'gitlab/src/services/MergeRequestDiscussions.js' {
  declare module.exports: $Exports<'gitlab/src/services/MergeRequestDiscussions'>;
}
declare module 'gitlab/src/services/MergeRequestNotes.js' {
  declare module.exports: $Exports<'gitlab/src/services/MergeRequestNotes'>;
}
declare module 'gitlab/src/services/MergeRequests.js' {
  declare module.exports: $Exports<'gitlab/src/services/MergeRequests'>;
}
declare module 'gitlab/src/services/Namespaces.js' {
  declare module.exports: $Exports<'gitlab/src/services/Namespaces'>;
}
declare module 'gitlab/src/services/NotificationSettings.js' {
  declare module.exports: $Exports<'gitlab/src/services/NotificationSettings'>;
}
declare module 'gitlab/src/services/PagesDomains.js' {
  declare module.exports: $Exports<'gitlab/src/services/PagesDomains'>;
}
declare module 'gitlab/src/services/Pipelines.js' {
  declare module.exports: $Exports<'gitlab/src/services/Pipelines'>;
}
declare module 'gitlab/src/services/PipelineSchedules.js' {
  declare module.exports: $Exports<'gitlab/src/services/PipelineSchedules'>;
}
declare module 'gitlab/src/services/PipelineScheduleVariables.js' {
  declare module.exports: $Exports<'gitlab/src/services/PipelineScheduleVariables'>;
}
declare module 'gitlab/src/services/ProjectAccessRequests.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectAccessRequests'>;
}
declare module 'gitlab/src/services/ProjectBadges.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectBadges'>;
}
declare module 'gitlab/src/services/ProjectCustomAttributes.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectCustomAttributes'>;
}
declare module 'gitlab/src/services/ProjectHooks.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectHooks'>;
}
declare module 'gitlab/src/services/ProjectImportExport.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectImportExport'>;
}
declare module 'gitlab/src/services/ProjectIssueBoards.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectIssueBoards'>;
}
declare module 'gitlab/src/services/ProjectMembers.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectMembers'>;
}
declare module 'gitlab/src/services/ProjectMilestones.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectMilestones'>;
}
declare module 'gitlab/src/services/Projects.js' {
  declare module.exports: $Exports<'gitlab/src/services/Projects'>;
}
declare module 'gitlab/src/services/ProjectSnippetAwardEmojis.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectSnippetAwardEmojis'>;
}
declare module 'gitlab/src/services/ProjectSnippetDiscussions.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectSnippetDiscussions'>;
}
declare module 'gitlab/src/services/ProjectSnippetNotes.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectSnippetNotes'>;
}
declare module 'gitlab/src/services/ProjectSnippets.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectSnippets'>;
}
declare module 'gitlab/src/services/ProjectVariables.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProjectVariables'>;
}
declare module 'gitlab/src/services/ProtectedBranches.js' {
  declare module.exports: $Exports<'gitlab/src/services/ProtectedBranches'>;
}
declare module 'gitlab/src/services/Repositories.js' {
  declare module.exports: $Exports<'gitlab/src/services/Repositories'>;
}
declare module 'gitlab/src/services/RepositoryFiles.js' {
  declare module.exports: $Exports<'gitlab/src/services/RepositoryFiles'>;
}
declare module 'gitlab/src/services/Runners.js' {
  declare module.exports: $Exports<'gitlab/src/services/Runners'>;
}
declare module 'gitlab/src/services/Search.js' {
  declare module.exports: $Exports<'gitlab/src/services/Search'>;
}
declare module 'gitlab/src/services/Services.js' {
  declare module.exports: $Exports<'gitlab/src/services/Services'>;
}
declare module 'gitlab/src/services/SidekiqMetrics.js' {
  declare module.exports: $Exports<'gitlab/src/services/SidekiqMetrics'>;
}
declare module 'gitlab/src/services/SystemHooks.js' {
  declare module.exports: $Exports<'gitlab/src/services/SystemHooks'>;
}
declare module 'gitlab/src/services/Tags.js' {
  declare module.exports: $Exports<'gitlab/src/services/Tags'>;
}
declare module 'gitlab/src/services/Todos.js' {
  declare module.exports: $Exports<'gitlab/src/services/Todos'>;
}
declare module 'gitlab/src/services/Triggers.js' {
  declare module.exports: $Exports<'gitlab/src/services/Triggers'>;
}
declare module 'gitlab/src/services/UserCustomAttributes.js' {
  declare module.exports: $Exports<'gitlab/src/services/UserCustomAttributes'>;
}
declare module 'gitlab/src/services/UserEmails.js' {
  declare module.exports: $Exports<'gitlab/src/services/UserEmails'>;
}
declare module 'gitlab/src/services/UserGPGKeys.js' {
  declare module.exports: $Exports<'gitlab/src/services/UserGPGKeys'>;
}
declare module 'gitlab/src/services/UserImpersonationTokens.js' {
  declare module.exports: $Exports<'gitlab/src/services/UserImpersonationTokens'>;
}
declare module 'gitlab/src/services/UserKeys.js' {
  declare module.exports: $Exports<'gitlab/src/services/UserKeys'>;
}
declare module 'gitlab/src/services/Users.js' {
  declare module.exports: $Exports<'gitlab/src/services/Users'>;
}
declare module 'gitlab/src/services/Version.js' {
  declare module.exports: $Exports<'gitlab/src/services/Version'>;
}
declare module 'gitlab/src/services/Wikis.js' {
  declare module.exports: $Exports<'gitlab/src/services/Wikis'>;
}
declare module 'gitlab/src/templates/index.js' {
  declare module.exports: $Exports<'gitlab/src/templates/index'>;
}
declare module 'gitlab/src/templates/ResourceAccessRequests.js' {
  declare module.exports: $Exports<'gitlab/src/templates/ResourceAccessRequests'>;
}
declare module 'gitlab/src/templates/ResourceAwardEmojis.js' {
  declare module.exports: $Exports<'gitlab/src/templates/ResourceAwardEmojis'>;
}
declare module 'gitlab/src/templates/ResourceBadges.js' {
  declare module.exports: $Exports<'gitlab/src/templates/ResourceBadges'>;
}
declare module 'gitlab/src/templates/ResourceCustomAttributes.js' {
  declare module.exports: $Exports<'gitlab/src/templates/ResourceCustomAttributes'>;
}
declare module 'gitlab/src/templates/ResourceDiscussions.js' {
  declare module.exports: $Exports<'gitlab/src/templates/ResourceDiscussions'>;
}
declare module 'gitlab/src/templates/ResourceIssueBoards.js' {
  declare module.exports: $Exports<'gitlab/src/templates/ResourceIssueBoards'>;
}
declare module 'gitlab/src/templates/ResourceMembers.js' {
  declare module.exports: $Exports<'gitlab/src/templates/ResourceMembers'>;
}
declare module 'gitlab/src/templates/ResourceMilestones.js' {
  declare module.exports: $Exports<'gitlab/src/templates/ResourceMilestones'>;
}
declare module 'gitlab/src/templates/ResourceNotes.js' {
  declare module.exports: $Exports<'gitlab/src/templates/ResourceNotes'>;
}
declare module 'gitlab/src/templates/ResourceTemplates.js' {
  declare module.exports: $Exports<'gitlab/src/templates/ResourceTemplates'>;
}
declare module 'gitlab/src/templates/ResourceVariables.js' {
  declare module.exports: $Exports<'gitlab/src/templates/ResourceVariables'>;
}
declare module 'gitlab/test/tests/bundles/GroupsBundle.js' {
  declare module.exports: $Exports<'gitlab/test/tests/bundles/GroupsBundle'>;
}
declare module 'gitlab/test/tests/bundles/ProjectsBundle.js' {
  declare module.exports: $Exports<'gitlab/test/tests/bundles/ProjectsBundle'>;
}
declare module 'gitlab/test/tests/bundles/UsersBundle.js' {
  declare module.exports: $Exports<'gitlab/test/tests/bundles/UsersBundle'>;
}
declare module 'gitlab/test/tests/infrastructure/BaseService.js' {
  declare module.exports: $Exports<'gitlab/test/tests/infrastructure/BaseService'>;
}
declare module 'gitlab/test/tests/infrastructure/Bundle.js' {
  declare module.exports: $Exports<'gitlab/test/tests/infrastructure/Bundle'>;
}
declare module 'gitlab/test/tests/infrastructure/RequestHelper.js' {
  declare module.exports: $Exports<'gitlab/test/tests/infrastructure/RequestHelper'>;
}
declare module 'gitlab/test/tests/services/ApplicationSettings.js' {
  declare module.exports: $Exports<'gitlab/test/tests/services/ApplicationSettings'>;
}
declare module 'gitlab/test/tests/services/Projects.js' {
  declare module.exports: $Exports<'gitlab/test/tests/services/Projects'>;
}
