// flow-typed signature: 2a0236dc42fcafcfd863c1981bc3d69e
// flow-typed version: <<STUB>>/global-tunnel-ng_v2.5.3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'global-tunnel-ng'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'global-tunnel-ng' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'global-tunnel-ng/lib/agents' {
  declare module.exports: any;
}

declare module 'global-tunnel-ng/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'global-tunnel-ng/index' {
  declare module.exports: $Exports<'global-tunnel-ng'>;
}
declare module 'global-tunnel-ng/index.js' {
  declare module.exports: $Exports<'global-tunnel-ng'>;
}
declare module 'global-tunnel-ng/lib/agents.js' {
  declare module.exports: $Exports<'global-tunnel-ng/lib/agents'>;
}
declare module 'global-tunnel-ng/test/index.js' {
  declare module.exports: $Exports<'global-tunnel-ng/test/index'>;
}
