// flow-typed signature: 61e720cb5913de87d7450192326235eb
// flow-typed version: <<STUB>>/in-publish_v^2.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'in-publish'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'in-publish' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'in-publish/in-install' {
  declare module.exports: any;
}

declare module 'in-publish/in-publish' {
  declare module.exports: any;
}

declare module 'in-publish/not-in-install' {
  declare module.exports: any;
}

declare module 'in-publish/not-in-publish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'in-publish/in-install.js' {
  declare module.exports: $Exports<'in-publish/in-install'>;
}
declare module 'in-publish/in-publish.js' {
  declare module.exports: $Exports<'in-publish/in-publish'>;
}
declare module 'in-publish/index' {
  declare module.exports: $Exports<'in-publish'>;
}
declare module 'in-publish/index.js' {
  declare module.exports: $Exports<'in-publish'>;
}
declare module 'in-publish/not-in-install.js' {
  declare module.exports: $Exports<'in-publish/not-in-install'>;
}
declare module 'in-publish/not-in-publish.js' {
  declare module.exports: $Exports<'in-publish/not-in-publish'>;
}
