// flow-typed signature: 89f5a7f465a65a890ee0c86c2b17be73
// flow-typed version: <<STUB>>/node-cache_v4.2.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-cache/lib/node_cache' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-cache/index' {
  declare module.exports: $Exports<'node-cache'>;
}
declare module 'node-cache/index.js' {
  declare module.exports: $Exports<'node-cache'>;
}
declare module 'node-cache/lib/node_cache.js' {
  declare module.exports: $Exports<'node-cache/lib/node_cache'>;
}
