// flow-typed signature: 8bb81e2aad8c5839f0671fb5d51efa53
// flow-typed version: <<STUB>>/repolinter_v0.7.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'repolinter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'repolinter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'repolinter/axioms/licensee' {
  declare module.exports: any;
}

declare module 'repolinter/axioms/linguist' {
  declare module.exports: any;
}

declare module 'repolinter/axioms/packagers' {
  declare module.exports: any;
}

declare module 'repolinter/bin/repolinter' {
  declare module.exports: any;
}

declare module 'repolinter/formatters/json_formatter' {
  declare module.exports: any;
}

declare module 'repolinter/formatters/symbol_formatter' {
  declare module.exports: any;
}

declare module 'repolinter/lib/file_system' {
  declare module.exports: any;
}

declare module 'repolinter/lib/licensee' {
  declare module.exports: any;
}

declare module 'repolinter/lib/linguist' {
  declare module.exports: any;
}

declare module 'repolinter/lib/result' {
  declare module.exports: any;
}

declare module 'repolinter/rules/directory-existence' {
  declare module.exports: any;
}

declare module 'repolinter/rules/file-contents' {
  declare module.exports: any;
}

declare module 'repolinter/rules/file-existence' {
  declare module.exports: any;
}

declare module 'repolinter/rules/file-not-contents' {
  declare module.exports: any;
}

declare module 'repolinter/rules/file-starts-with' {
  declare module.exports: any;
}

declare module 'repolinter/rules/file-type-exclusion' {
  declare module.exports: any;
}

declare module 'repolinter/rules/git-grep-commits' {
  declare module.exports: any;
}

declare module 'repolinter/rules/git-grep-log' {
  declare module.exports: any;
}

declare module 'repolinter/rules/git-list-tree' {
  declare module.exports: any;
}

declare module 'repolinter/rules/git-working-tree' {
  declare module.exports: any;
}

declare module 'repolinter/rules/license-detectable-by-licensee' {
  declare module.exports: any;
}

declare module 'repolinter/tests/axioms/packagers_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/formatters/json_formatter_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/formatters/symbol_formatter_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/lib/file_system_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/package/repolinter_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/rules/file_contents_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/rules/file_existence_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/rules/file_not_contents_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/rules/file_starts_with_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/rules/file_type_exclusion_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/rules/git_grep_commits_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/rules/git_grep_log_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/rules/git_list_tree_tests' {
  declare module.exports: any;
}

declare module 'repolinter/tests/rules/git_working_tree_tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'repolinter/axioms/licensee.js' {
  declare module.exports: $Exports<'repolinter/axioms/licensee'>;
}
declare module 'repolinter/axioms/linguist.js' {
  declare module.exports: $Exports<'repolinter/axioms/linguist'>;
}
declare module 'repolinter/axioms/packagers.js' {
  declare module.exports: $Exports<'repolinter/axioms/packagers'>;
}
declare module 'repolinter/bin/repolinter.js' {
  declare module.exports: $Exports<'repolinter/bin/repolinter'>;
}
declare module 'repolinter/formatters/json_formatter.js' {
  declare module.exports: $Exports<'repolinter/formatters/json_formatter'>;
}
declare module 'repolinter/formatters/symbol_formatter.js' {
  declare module.exports: $Exports<'repolinter/formatters/symbol_formatter'>;
}
declare module 'repolinter/index' {
  declare module.exports: $Exports<'repolinter'>;
}
declare module 'repolinter/index.js' {
  declare module.exports: $Exports<'repolinter'>;
}
declare module 'repolinter/lib/file_system.js' {
  declare module.exports: $Exports<'repolinter/lib/file_system'>;
}
declare module 'repolinter/lib/licensee.js' {
  declare module.exports: $Exports<'repolinter/lib/licensee'>;
}
declare module 'repolinter/lib/linguist.js' {
  declare module.exports: $Exports<'repolinter/lib/linguist'>;
}
declare module 'repolinter/lib/result.js' {
  declare module.exports: $Exports<'repolinter/lib/result'>;
}
declare module 'repolinter/rules/directory-existence.js' {
  declare module.exports: $Exports<'repolinter/rules/directory-existence'>;
}
declare module 'repolinter/rules/file-contents.js' {
  declare module.exports: $Exports<'repolinter/rules/file-contents'>;
}
declare module 'repolinter/rules/file-existence.js' {
  declare module.exports: $Exports<'repolinter/rules/file-existence'>;
}
declare module 'repolinter/rules/file-not-contents.js' {
  declare module.exports: $Exports<'repolinter/rules/file-not-contents'>;
}
declare module 'repolinter/rules/file-starts-with.js' {
  declare module.exports: $Exports<'repolinter/rules/file-starts-with'>;
}
declare module 'repolinter/rules/file-type-exclusion.js' {
  declare module.exports: $Exports<'repolinter/rules/file-type-exclusion'>;
}
declare module 'repolinter/rules/git-grep-commits.js' {
  declare module.exports: $Exports<'repolinter/rules/git-grep-commits'>;
}
declare module 'repolinter/rules/git-grep-log.js' {
  declare module.exports: $Exports<'repolinter/rules/git-grep-log'>;
}
declare module 'repolinter/rules/git-list-tree.js' {
  declare module.exports: $Exports<'repolinter/rules/git-list-tree'>;
}
declare module 'repolinter/rules/git-working-tree.js' {
  declare module.exports: $Exports<'repolinter/rules/git-working-tree'>;
}
declare module 'repolinter/rules/license-detectable-by-licensee.js' {
  declare module.exports: $Exports<'repolinter/rules/license-detectable-by-licensee'>;
}
declare module 'repolinter/tests/axioms/packagers_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/axioms/packagers_tests'>;
}
declare module 'repolinter/tests/formatters/json_formatter_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/formatters/json_formatter_tests'>;
}
declare module 'repolinter/tests/formatters/symbol_formatter_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/formatters/symbol_formatter_tests'>;
}
declare module 'repolinter/tests/lib/file_system_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/lib/file_system_tests'>;
}
declare module 'repolinter/tests/package/repolinter_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/package/repolinter_tests'>;
}
declare module 'repolinter/tests/rules/file_contents_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/rules/file_contents_tests'>;
}
declare module 'repolinter/tests/rules/file_existence_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/rules/file_existence_tests'>;
}
declare module 'repolinter/tests/rules/file_not_contents_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/rules/file_not_contents_tests'>;
}
declare module 'repolinter/tests/rules/file_starts_with_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/rules/file_starts_with_tests'>;
}
declare module 'repolinter/tests/rules/file_type_exclusion_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/rules/file_type_exclusion_tests'>;
}
declare module 'repolinter/tests/rules/git_grep_commits_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/rules/git_grep_commits_tests'>;
}
declare module 'repolinter/tests/rules/git_grep_log_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/rules/git_grep_log_tests'>;
}
declare module 'repolinter/tests/rules/git_list_tree_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/rules/git_list_tree_tests'>;
}
declare module 'repolinter/tests/rules/git_working_tree_tests.js' {
  declare module.exports: $Exports<'repolinter/tests/rules/git_working_tree_tests'>;
}
