// flow-typed signature: 7501ed861cf48b331e8020384a33c187
// flow-typed version: <<STUB>>/verdaccio_v3.8.6/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'verdaccio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'verdaccio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'verdaccio/build/api/debug/index' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/dist-tags' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/package' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/ping' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/publish' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/search' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/user' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/api/whoami' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/endpoint/index' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/index' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/middleware' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/web/api' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/web/endpoint/package' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/web/endpoint/search' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/web/endpoint/user' {
  declare module.exports: any;
}

declare module 'verdaccio/build/api/web/index' {
  declare module.exports: any;
}

declare module 'verdaccio/build/config/env' {
  declare module.exports: any;
}

declare module 'verdaccio/build/index' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/auth-utils' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/auth' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/bootstrap' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/cli' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/config-path' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/config-utils' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/config' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/constants' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/crypto-utils' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/local-storage' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/logger' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/metadata-utils' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/notify' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/plugin-loader' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/search' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/status-cats' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/storage-utils' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/storage' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/up-storage' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/uplink-util' {
  declare module.exports: any;
}

declare module 'verdaccio/build/lib/utils' {
  declare module.exports: any;
}

declare module 'verdaccio/build/utils/string' {
  declare module.exports: any;
}

declare module 'verdaccio/build/utils/user' {
  declare module.exports: any;
}

declare module 'verdaccio/jest.config' {
  declare module.exports: any;
}

declare module 'verdaccio/static/1.75c3153d5b5f165d0978' {
  declare module.exports: any;
}

declare module 'verdaccio/static/3.75c3153d5b5f165d0978' {
  declare module.exports: any;
}

declare module 'verdaccio/static/4.75c3153d5b5f165d0978' {
  declare module.exports: any;
}

declare module 'verdaccio/static/5.75c3153d5b5f165d0978' {
  declare module.exports: any;
}

declare module 'verdaccio/static/6.75c3153d5b5f165d0978' {
  declare module.exports: any;
}

declare module 'verdaccio/static/main.75c3153d5b5f165d0978' {
  declare module.exports: any;
}

declare module 'verdaccio/static/manifest.75c3153d5b5f165d0978' {
  declare module.exports: any;
}

declare module 'verdaccio/static/vendors.75c3153d5b5f165d0978' {
  declare module.exports: any;
}

// Filename aliases
declare module 'verdaccio/build/api/debug/index.js' {
  declare module.exports: $Exports<'verdaccio/build/api/debug/index'>;
}
declare module 'verdaccio/build/api/endpoint/api/dist-tags.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/dist-tags'>;
}
declare module 'verdaccio/build/api/endpoint/api/package.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/package'>;
}
declare module 'verdaccio/build/api/endpoint/api/ping.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/ping'>;
}
declare module 'verdaccio/build/api/endpoint/api/publish.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/publish'>;
}
declare module 'verdaccio/build/api/endpoint/api/search.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/search'>;
}
declare module 'verdaccio/build/api/endpoint/api/user.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/user'>;
}
declare module 'verdaccio/build/api/endpoint/api/whoami.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/api/whoami'>;
}
declare module 'verdaccio/build/api/endpoint/index.js' {
  declare module.exports: $Exports<'verdaccio/build/api/endpoint/index'>;
}
declare module 'verdaccio/build/api/index.js' {
  declare module.exports: $Exports<'verdaccio/build/api/index'>;
}
declare module 'verdaccio/build/api/middleware.js' {
  declare module.exports: $Exports<'verdaccio/build/api/middleware'>;
}
declare module 'verdaccio/build/api/web/api.js' {
  declare module.exports: $Exports<'verdaccio/build/api/web/api'>;
}
declare module 'verdaccio/build/api/web/endpoint/package.js' {
  declare module.exports: $Exports<'verdaccio/build/api/web/endpoint/package'>;
}
declare module 'verdaccio/build/api/web/endpoint/search.js' {
  declare module.exports: $Exports<'verdaccio/build/api/web/endpoint/search'>;
}
declare module 'verdaccio/build/api/web/endpoint/user.js' {
  declare module.exports: $Exports<'verdaccio/build/api/web/endpoint/user'>;
}
declare module 'verdaccio/build/api/web/index.js' {
  declare module.exports: $Exports<'verdaccio/build/api/web/index'>;
}
declare module 'verdaccio/build/config/env.js' {
  declare module.exports: $Exports<'verdaccio/build/config/env'>;
}
declare module 'verdaccio/build/index.js' {
  declare module.exports: $Exports<'verdaccio/build/index'>;
}
declare module 'verdaccio/build/lib/auth-utils.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/auth-utils'>;
}
declare module 'verdaccio/build/lib/auth.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/auth'>;
}
declare module 'verdaccio/build/lib/bootstrap.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/bootstrap'>;
}
declare module 'verdaccio/build/lib/cli.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/cli'>;
}
declare module 'verdaccio/build/lib/config-path.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/config-path'>;
}
declare module 'verdaccio/build/lib/config-utils.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/config-utils'>;
}
declare module 'verdaccio/build/lib/config.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/config'>;
}
declare module 'verdaccio/build/lib/constants.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/constants'>;
}
declare module 'verdaccio/build/lib/crypto-utils.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/crypto-utils'>;
}
declare module 'verdaccio/build/lib/local-storage.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/local-storage'>;
}
declare module 'verdaccio/build/lib/logger.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/logger'>;
}
declare module 'verdaccio/build/lib/metadata-utils.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/metadata-utils'>;
}
declare module 'verdaccio/build/lib/notify.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/notify'>;
}
declare module 'verdaccio/build/lib/plugin-loader.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/plugin-loader'>;
}
declare module 'verdaccio/build/lib/search.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/search'>;
}
declare module 'verdaccio/build/lib/status-cats.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/status-cats'>;
}
declare module 'verdaccio/build/lib/storage-utils.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/storage-utils'>;
}
declare module 'verdaccio/build/lib/storage.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/storage'>;
}
declare module 'verdaccio/build/lib/up-storage.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/up-storage'>;
}
declare module 'verdaccio/build/lib/uplink-util.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/uplink-util'>;
}
declare module 'verdaccio/build/lib/utils.js' {
  declare module.exports: $Exports<'verdaccio/build/lib/utils'>;
}
declare module 'verdaccio/build/utils/string.js' {
  declare module.exports: $Exports<'verdaccio/build/utils/string'>;
}
declare module 'verdaccio/build/utils/user.js' {
  declare module.exports: $Exports<'verdaccio/build/utils/user'>;
}
declare module 'verdaccio/index' {
  declare module.exports: $Exports<'verdaccio'>;
}
declare module 'verdaccio/index.js' {
  declare module.exports: $Exports<'verdaccio'>;
}
declare module 'verdaccio/jest.config.js' {
  declare module.exports: $Exports<'verdaccio/jest.config'>;
}
declare module 'verdaccio/static/1.75c3153d5b5f165d0978.js' {
  declare module.exports: $Exports<'verdaccio/static/1.75c3153d5b5f165d0978'>;
}
declare module 'verdaccio/static/3.75c3153d5b5f165d0978.js' {
  declare module.exports: $Exports<'verdaccio/static/3.75c3153d5b5f165d0978'>;
}
declare module 'verdaccio/static/4.75c3153d5b5f165d0978.js' {
  declare module.exports: $Exports<'verdaccio/static/4.75c3153d5b5f165d0978'>;
}
declare module 'verdaccio/static/5.75c3153d5b5f165d0978.js' {
  declare module.exports: $Exports<'verdaccio/static/5.75c3153d5b5f165d0978'>;
}
declare module 'verdaccio/static/6.75c3153d5b5f165d0978.js' {
  declare module.exports: $Exports<'verdaccio/static/6.75c3153d5b5f165d0978'>;
}
declare module 'verdaccio/static/main.75c3153d5b5f165d0978.js' {
  declare module.exports: $Exports<'verdaccio/static/main.75c3153d5b5f165d0978'>;
}
declare module 'verdaccio/static/manifest.75c3153d5b5f165d0978.js' {
  declare module.exports: $Exports<'verdaccio/static/manifest.75c3153d5b5f165d0978'>;
}
declare module 'verdaccio/static/vendors.75c3153d5b5f165d0978.js' {
  declare module.exports: $Exports<'verdaccio/static/vendors.75c3153d5b5f165d0978'>;
}
